def generate_gcode(operation: str, params: dict) -> str:
    """
    Minimal placeholder to prove Python integration works.
    operation: e.g. 'facing', 'drilling', 'pocket'
    params: dict with keys like: feed, speed, depth, tool_diameter, safe_z, work_z
    """
    op = operation.lower()
    feed = params.get("feed", 200)
    speed = params.get("speed", 1000)
    safe_z = params.get("safe_z", 5.0)
    work_z = params.get("work_z", -1.0)
    x = params.get("x", 0.0)
    y = params.get("y", 0.0)

    lines = [
        "(G-code generated by Chaquopy Python module)",
        "G21",
        "G90",
        f"S{speed} M3",
        f"G0 Z{safe_z}",
        f"G0 X{x} Y{y}",
    ]

    if op == "drilling":
        peck = params.get("peck", 0.0)
        if peck > 0:
            lines += [
                f"G83 X{x} Y{y} Z{work_z} R{safe_z} Q{peck} F{feed}",
            ]
        else:
            lines += [
                f"G81 X{x} Y{y} Z{work_z} R{safe_z} F{feed}",
            ]
    else:
        # Fallback simple linear plunge
        lines += [
            f"G1 Z{work_z} F{feed}",
            "G4 P0.2",
            f"G0 Z{safe_z}",
        ]

    lines += [
        "M5",
        "G0 Z{:.3f}".format(safe_z),
        "M30",
    ]
    return "\n".join(lines)


def suggest_machine_and_tool(material: str, diameter: float) -> dict:
    """
    Placeholder: returns a stub suggestion. Replace with real logic later.
    """
    machine = "Generic 3-axis CNC"
    tool = {
        "type": "End Mill",
        "diameter": diameter,
        "coating": "TiAlN" if material.lower() in ("steel", "stainless") else "Uncoated",
    }
    return {"machine": machine, "tool": tool}


